codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        # basic
        target: 0
        threshold: 0
    patch:
      default:
        target: 0
        threshold: 0

ignore:
  - "Density3D/tests/"
  - "Density3D/_version.py"
  - "Density3D/__init__.py"
  - "Density3D/cli/"
